// ── Reports module — read-side báo cáo (dashboard, revenue, export, shift-day) ─────
export type {
  ReportingRepository,
  ReportingStore,
  DashboardInput,
  DashboardScope,
  DashboardData,
  PaymentMethodRow,
  ItemTypeRow,
  RevenueInput,
  RevenueResult,
  RevenueRow,
  SessionExportRow,
  ShiftDayGroupInput,
  ShiftDayGroup,
  ShiftDayShift,
  TrendData,
  TrendItemType,
  TrendHourRow,
  TrendDayRow,
  TrendComparison,
  TrendTotals,
  TopProductsInput,
  TopProductRow,
  TopProductsResult,
} from './ports'
